### ISSUE TITLE
HEROKU_API_KEY usage differences from 2.0.X to 3.0.X

### ISSUE THREAD

**Issue by rubensa** [heroku/heroku-maven-plugin#70]
**HEROKU_API_KEY** set as environment variable in **Travis CI**

One artifact deployed from **Travis CI** using **heroku-maven-plugin** version **2.0.5** -> **OK**
Same exact artifact deployed from **Travis CI** using **heroku-maven-plugin** version **3.0.2** -> **Error**

```[ERROR] Failed to execute goal com.heroku.sdk:heroku-maven-plugin:3.0.2:deploy (default-cli) on project project-name: Unexpected error!: peer not authenticated -> [Help 1]```

Could not find info about **HEROKU_API_KEY** change or deprecation.

**Comment by rubensa** [comment]
With verison **2.0.16** deploys without problems.

From my **.travis.yml**:
```yaml
language: java

sudo: false

cache:
  directories:
    - $HOME/.m2/repository

jdk:
- openjdk11

services:
- docker

addons:
  sonarcloud:
    organization: "my-org"

before_install:
- mvn clean
- echo "$DOCKER_PASSWORD" | docker login  -u "$DOCKER_ID" --password-stdin
- docker pull adoptopenjdk/openjdk11:alpine-jre

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=my-project package dockerfile:build verify dockerfile:push heroku:deploy

after_success:
- bash <(curl -s https://codecov.io/bash)
  # Generating Site
- mvn site
```

Form my **pom.xml**:
```xml
      <!--
      Heroku Maven Plugin - Deploy Java applications directly to Heroku without pushing to a Git repository
      https://github.com/heroku/heroku-maven-plugin
      -->
      <plugin>
        <groupId>com.heroku.sdk</groupId>
        <artifactId>heroku-maven-plugin</artifactId>
        <configuration>
          <appName>my-app</appName>
          <jdkVersion>11</jdkVersion>
          <processTypes>
            <web>java $JAVA_OPTS -jar -Dserver.port=$PORT ${full-artifact-name}</web>
          </processTypes>
          <includeTarget>false</includeTarget>
          <includes>
            <include>${full-artifact-name}</include>
          </includes>
        </configuration>
      </plugin>
```

The app is a Spring Boot 2.3.0.RELEASE application.
